### DISCUSSION TITLE
How to remove peers?

### DISCUSSION THREAD

**Discussion by lightningspirit** [dswd/vpncloud#215] [Q&A] [answered]
Our setup has 9 nodes sharing the same vpncloud mesh. We started the deployment using public internet interface for communication, however nowadays they are sharing an internal network (not secured, hence we still need to use vpncloud) and gradually moved the configurations to use their internal network IPs.

Seeing stats everything looks great but we still see both internal and public IPs in the `peers` and `forwarding_table` sections:
```
peers:
  - "10.0.0.2:3210": { ttl_secs: 274, crypto: AES128 }
  - "10.0.0.9:3210": { ttl_secs: 262, crypto: AES128 }
  - "<public_ip>:3210": { ttl_secs: 250, crypto: AES128 }
  - "10.0.0.4:3210": { ttl_secs: 289, crypto: AES128 }
  - "10.0.0.7:3210": { ttl_secs: 246, crypto: CHACHA20 }
  - "10.0.0.5:3210": { ttl_secs: 250, crypto: AES128 }
  - "<public_ip>:3210": { ttl_secs: 246, crypto: CHACHA20 }
  - "<public_ip>:3210": { ttl_secs: 220, crypto: AES128 }
  - "<public_ip>:3210": { ttl_secs: 289, crypto: AES128 }
  - "10.0.0.6:3210": { ttl_secs: 220, crypto: AES128 }
  - "10.0.0.8:3210": { ttl_secs: 220, crypto: AES128 }
  - "<public_ip>:3210": { ttl_secs: 262, crypto: AES128 }

forwarding_table:
  claims:
    - "10.67.89.52/32": { peer: "10.0.0.5:3210", timeout: 250 }
    - "10.67.89.52/32": { peer: "<public_ip>:3210", timeout: 250 }
    - "10.67.89.12/32": { peer: "10.0.0.6:3210", timeout: 220 }
    - "10.67.89.12/32": { peer: "<public_ip>:3210", timeout: 220 }
    - "10.67.89.13/32": { peer: "10.0.0.7:3210", timeout: 246 }
    - "10.67.89.13/32": { peer: "<public_ip>:3210", timeout: 246 }
    - "10.67.89.51/32": { peer: "10.0.0.2:3210", timeout: 274 }
    - "10.67.89.53/32": { peer: "10.0.0.4:3210", timeout: 289 }
    - "10.67.89.53/32": { peer: "<public_ip>:3210", timeout: 289 }
    - "10.67.89.31/32": { peer: "10.0.0.8:3210", timeout: 220 }
    - "10.67.89.32/32": { peer: "10.0.0.9:3210", timeout: 262 }
    - "10.67.89.32/32": { peer: "<public_ip>:3210", timeout: 262 }
  cache:
    - "10.67.89.52": { peer: "10.0.0.5:3210", timeout: 250 }
    - "10.67.89.31": { peer: "10.0.0.8:3210", timeout: 220 }
    - "10.67.89.32": { peer: "10.0.0.9:3210", timeout: 262 }
    - "10.67.89.13": { peer: "10.0.0.7:3210", timeout: 246 }
    - "10.67.89.53": { peer: "10.0.0.4:3210", timeout: 289 }
    - "10.67.89.51": { peer: "10.0.0.2:3210", timeout: 274 }
    - "10.67.89.12": { peer: "10.0.0.6:3210", timeout: 220 }
```

My question is, how can I remove the public IPs from `peers` and `forwarding_table` without forcefully restart every node at the same time?
