### DISCUSSION TITLE
VPNCloud publishes internal ip addresses

### DISCUSSION THREAD

**Discussion by TomasGlgg** [dswd/vpncloud#266] [Q&A] [answered]
I use vpncloud on several local networks, including those with a gray ip address, and some local networks cannot communicate with others due to the fact that internal addresses from other local networks appear in their peers.

```
peer_traffic:                                                                                                      
  - peer: "192.168.11.4:50900"                                                                                     
    in: { display: "0 B/s", bytes: 0, packets: 0 }                                                                 
    out: { display: "82 B/s", bytes: 4960, packets: 32 }
  - peer: "192.168.1.4:50841"                                                                                      
    in: { display: "0 B/s", bytes: 0, packets: 0 }                                                                 
    out: { display: "82 B/s", bytes: 4960, packets: 32 }                                                           
  - peer: "192.168.1.2:50830"                                                                                      
    in: { display: "0 B/s", bytes: 0, packets: 0 }                                                                 
    out: { display: "82 B/s", bytes: 4960, packets: 32 }                                                           
  - peer: "192.168.100.2:50842"                                                                                    
    in: { display: "0 B/s", bytes: 0, packets: 0 }                                                              
    out: { display: "82 B/s", bytes: 4960, packets: 32 }
```

How can this be avoided?
