### ISSUE TITLE
## Bug Report: Duplicate MAC Addresses on TAP Interfaces Causing Network Conflicts

### ISSUE THREAD

**Issue by fumufu86** [dswd/vpncloud#381]
### Describe the bug
**Description**
When using TAP interfaces, there is a recurring issue where MAC addresses are generated identically for multiple interfaces. This results in network conflicts and connectivity problems, particularly in environments with a large number of virtual devices.

**Steps to Reproduce**
1. Create multiple TAP interfaces in a network environment using [software/tool/method].
2. Observe the MAC addresses assigned to each TAP interface.
3. Note that some or all interfaces receive identical MAC addresses.

**Expected Behavior**
Each TAP interface should receive a unique MAC address to ensure proper network operations and avoid conflicts.

**Actual Behavior**
Duplicate MAC addresses are assigned to different TAP interfaces, causing network conflicts and potential connectivity disruptions.

### Details of your setup

**VpnCloud version:**
VpnCloud v2.2.0
**Description of your VPN setup**
- How many nodes?
3 or 11
- Any NAT involved?
no
- Any custom routing?
OSPF

**Config file contents**
normally in `/etc/vpncloud/MYNET.net`
:bangbang: make sure to mask (`***`) passwords and public IPs/hostnames :bangbang:
```
---
device:
  type: tap
  name: tap-vpncloud
  path: ~
  fix-rp-filter: false
mode: switch
switch-timeout: 300
ip: "172.31.1.201-203/24"
ifup: ~
ifdown: ~
crypto:
  password: "strong-password"
  private-key: ~
  public-key: ~
  trusted-keys: []
  algorithms:
    - CHACHA20
listen: "3210"
peers:
  - x.x.x.x:3210
  - y.y.y.y:3210
  - z.z.z.z:3210
peer-timeout: 10
keepalive: 3
beacon:
  store: ~
  load: ~
  interval: 600
  password: "strong-password"
claims:
  - 0.0.0.0/0
auto-claim: true
port-forwarding: false
pid-file: y
stats-file: y
statsd:
  server: ~
  prefix: ~
user: ~
group: ~
hook: ~
hooks: {}
```
**Log entries**
normally in `/var/log/vpncloud.MYNET.log`
