### ISSUE TITLE
Handling multiple NATs.

### ISSUE THREAD

**Issue by i1i1** [dswd/vpncloud#47]
I've got some problem with connecting 3 devices together. Here is my sample configuration:
``` yaml
port: 3210

peer_timeout: 1800
dst_timeout: 300

magic: "76706e01"

device_name: "vpncloud%d"
device_type: tap

mode: normal

subnets:
  - 10.0.0.0/24

ifdown: "ifconfig $IFNAME down"

user: "root"
group: "root"
```

There are 3 nodes, only one of them has public ip address(H2):
``` 
 ______                  ______                   ______
|      |      <x|-------|      |--------|x>      |      |
|  H1  |        |       |  H2  |        |        |  H3  |
|______|--------|------>|______|<-------|--------|______|
```

Host 1 can't talk to host 3.

Configuration on host 1:
``` yaml
peers:
  - host2

ifup: "ifconfig $IFNAME 10.0.0.1/24 mtu 1400"
```
Configuration on host 2:
``` yaml
ifup: "ifconfig $IFNAME 10.0.0.2/24 mtu 1400"
```
Configuration on host 3:
``` yaml
peers:
  - host2

ifup: "ifconfig $IFNAME 10.0.0.3/24 mtu 1400"
```

After enabling service on all 3 hosts I can reach host 2 from host 1 and host 3 and vice versa -- host 2 can reach host 1 and host 3. But host 1 can't reach host 3:
``` sh
$ # pinging host 3 from host 1
$ ping 10.0.0.3
PING 10.0.0.3 (10.0.0.3) 56(84) bytes of data.
From 10.0.0.1 icmp_seq=1 Destination Host Unreachable
From 10.0.0.1 icmp_seq=2 Destination Host Unreachable
From 10.0.0.1 icmp_seq=3 Destination Host Unreachable
```

Is `vpncloud` suitable for handling such kind of networks?
